name: Build Helm Package
description: |
  Builds and publishes a Helm chart package to Knox's S3 Helm registry. Additionally, this action pushes a Helm chart
  package to Knox's legacy S3 registry (required until a full migration to the AWS LZ is complete).

inputs:
  # TODO: We should default this when GitHub allows for private actions/workflows repos for non-enterprise customers...
  aws-build-role-arn:
    description: IAM Role ARN to assume to publish Helm package.
    required: true
  helm-directory:
    description: Helm chart directory (within current repo).
    required: true
  helm-package-name:
    description: Helm chart package name.
    required: true
  # Optional Inputs
  aws-region:
    description: AWS Region for S3 registry access.
    default: us-east-2
    required: false
  helm-repo-name:
    description: Helm repository name (within the Helm registry).
    default: knox
    required: false
  legacy-aws-build-role-arn:
    description: Account IAM Role ARN to assume to publish Helm package to legacy account.
    required: false
  legacy-helm-repo-name:
    description: |
      Helm repository name within legacy account registry (this is different for each development team).
      inter-bank: monetae
      gomono:     stable/identity
      sandbox:    stable/identity
    required: false

runs:
  using: composite
  steps:
    - name: Install Helm
      shell: bash
      run: |
        sudo snap install helm --classic
        helm plugin install https://github.com/hypnoglow/helm-s3.git --version 0.14.0 || echo "plugin already installed"

    - name: Authenticate via AWS IAM OIDC Provider
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: ${{ inputs.aws-build-role-arn }}
        aws-region: ${{ inputs.aws-region }}

    - name: Build / Publish Helm Package
      shell: bash
      run: |
        helm repo add ${{ inputs.helm-repo-name }} s3://knox.us-east-2.helm-registry/${{ inputs.helm-repo-name }}
        helm package ${{ inputs.helm-directory }}
        helm s3 push --force ${{ inputs.helm-package-name }}-*.tgz ${{ inputs.helm-repo-name }}

    - name: (Legacy) Authenticate via AWS IAM OIDC Provider
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: ${{ inputs.legacy-aws-build-role-arn }}
        aws-region: ${{ inputs.aws-region }}

    - name: (Legacy) Build / Publish Helm Package
      shell: bash
      run: |
        helm repo add legacy-${{ inputs.helm-repo-name }} s3://knox-helm-charts/${{ inputs.legacy-helm-repo-name }}
        helm package ${{ inputs.helm-directory }}
        helm s3 push --force ${{ inputs.helm-package-name }}-*.tgz legacy-${{ inputs.helm-repo-name }}
