name: Terraform Module Build Workflow

on:
  workflow_call:
    inputs:
      aws-region:
        type: string
        description: AWS Region for Terraform state, etc. (i.e. us-east-1).
        required: true
      apply-examples-ci:
        type: boolean
        description: Boolean indicating whether or not to apply examples/ci.
        required: false
        default: true
    secrets:
      build-role-arn:
        description: IAM Role ARN to assume for build-related tasks.
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  lint-tasks:
    name: Lint Tasks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Authenticate AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.build-role-arn }}
          aws-region: ${{ inputs.aws-region }}

      - name: Run CI Tasks
        run: make module.ci

  apply-examples-ci:
    name: Apply examples/ci
    runs-on: ubuntu-latest
    needs:
      - lint-tasks
    if: ${{ inputs.apply-examples-ci }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Authenticate AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.build-role-arn }}
          aws-region: ${{ inputs.aws-region }}

      - name: Terraform Apply examples/ci
        run: |
          make module.example.apply
          make module.example.destroy
